### ISSUE TITLE
AbstractMethodError

### ISSUE THREAD

**Issue by lyzcom** [ksvc/KSYMediaEditorKit_Android#20]
在 **小米 MI 5** (android 7.0) 出现以下错误
java.lang.AbstractMethodError: abstract method "void com.ksyun.media.streamer.kit.KSYStreamer$OnErrorListener.onError(int, int, int)"
java.lang.AbstractMethodError: abstract method "void com.ksyun.media.streamer.kit.KSYStreamer$OnErrorListener.onError(int, int, int)"
at com.ksyun.media.streamer.kit.KSYStreamer$3.onError(KSYStreamer.java:301)
at com.ksyun.media.streamer.capture.CameraCapture$a.handleMessage(CameraCapture.java:762)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6114)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

**Comment by zanxiaofei** [comment]
已经，解决，麻烦使用0.6.0版本
